--liquibase formatted sql
--changeset Rob:create_buyers context:production,test

CREATE TABLE core.task (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    parent_id   bigint,
    goal        text    NOT NULL,
    params      text,
    error       text,
    status      text    NOT NULL,
    stage       Int     NOT NULL,
    executed    Boolean NOT NULL
);

-- COMMENT ON COLUMN core.buyers.id IS 'Id';
-- COMMENT ON COLUMN core.buyers.email IS 'Email';

-- ALTER TABLE core.buyers OWNER TO deer;
