--liquibase formatted sql
--changeset Rob:create_buyers context:production,test

CREATE TABLE core.task (
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description text,
    parent_id bigint,
    goal text,
    params text,
    error text,
    status text,
    stage Int,
    executed Boolean
);

-- COMMENT ON COLUMN core.buyers.id IS 'Id';
-- COMMENT ON COLUMN core.buyers.email IS 'Email';

-- ALTER TABLE core.buyers OWNER TO deer;
